const { chromium } = require('playwright'); const path=require('path'); const fs=require('fs'); const http=require('http');
const three = fs.readFileSync(path.join(__dirname,'..','node_modules/three/build/three.min.js'));
const server = http.createServer((q,res)=>{res.writeHead(200,{'content-type':'text/html'});res.end(fs.readFileSync(path.join(__dirname,'..','dist/index.html')));}).listen(8768);
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});const page=await b.newPage({viewport:{width:1400,height:860}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message)); page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('**/three.min.js',r=>r.fulfill({status:200,contentType:'application/javascript',body:three}));
await page.route('**/fonts.googleapis.com/**',r=>r.fulfill({status:200,contentType:'text/css',body:''}));
await page.goto('http://localhost:8768/');await page.waitForTimeout(1200);
await page.click('#btn-start');await page.waitForTimeout(300);await page.screenshot({path:'test/m1-first.png'});
await page.evaluate(()=>{S.party.candy=900;S.party.runCount=3;S.party.tabsPaid=1;S.party.nodes={mag_cap:2,damage:1};S.party.lastRun={banked:466,taken:0,shots:25,sweetHits:8,crits:5,bodyHits:8,misses:9,breaks:13,spill:36,bestStreak:4,toss:false};S.party.tabs[1].dueLeft=0;renderMailbox();});
await page.waitForTimeout(200);await page.screenshot({path:'test/m2-mid.png'});
await page.click('g.node[data-node="sweet_refund"]',{force:true});await page.waitForTimeout(200);await page.screenshot({path:'test/m3-node.png'});
const r=await page.evaluate(()=>{const before=S.party.candy; selectNode(NODE_BY_ID.sweet_refund); return {before, after:S.party.candy, rank:rank('sweet_refund')};});
console.log('double-click buy:',JSON.stringify(r));
await page.click('.chips button[data-sheet="charms"]');await page.waitForTimeout(200);await page.screenshot({path:'test/m4-sheet.png'});
await page.keyboard.press('Escape');
await page.setViewportSize({width:820,height:900});await page.waitForTimeout(300);await page.screenshot({path:'test/m5-narrow.png',fullPage:false});
console.log('ERRORS:',errors.length?errors.join('\n'):'none');
await b.close();server.close();})();
